# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "puphpet/debian75-x32"
  # Note, for vm.box_url, you only need to do this on the very first vagrant
  # up with this box. If for later on another project you need this base
  # box again, you will not need it, because vagrant will already have
  # downloaded and kept it in cache. Be aware this is a 64-bit version.
  config.vm.box_url = "ftp://ftp.lugons.org/vagrant/debian-7.5.0-x86_64.box"
  config.vm.provision:shell, :inline => <<-END
    set -e
    for s in /vagrant/provisioning/??-*.sh ; do $s ; done
END
  config.vm.network :forwarded_port, host: 9090, guest: 80 # Apache server

  config.vm.hostname = "name.dev"
end